import { z } from "zod";
import { AssetType, ConfidentialityLevel, PropertySourceType, PropertyStatus } from "@prisma/client";
const optionalTrimmedString = z.string().trim().transform((v) => (v === "" ? undefined : v)).optional();
const optionalNullableTrimmedString = z.string().trim().transform((v) => (v === "" ? null : v)).nullable().optional();
const optionalDecimalString = z.union([z.string(), z.number()]).optional().transform((v) => { if (v === undefined || v === null || v === "") return undefined; return String(v); });
export const createPropertySchema = z.object({ internalTitle: z.string().trim().min(2, "Titre interne requis"), propertyReference: optionalTrimmedString, status: z.nativeEnum(PropertyStatus).default(PropertyStatus.DRAFT), confidentialityLevel: z.nativeEnum(ConfidentialityLevel).default(ConfidentialityLevel.INTERNAL), sourceType: z.nativeEnum(PropertySourceType).default(PropertySourceType.MANUAL), assetType: z.nativeEnum(AssetType).default(AssetType.LOCAL_COMMERCIAL), addressLine1: optionalNullableTrimmedString, postalCode: optionalNullableTrimmedString, city: optionalNullableTrimmedString, arrondissement: optionalNullableTrimmedString, neighborhood: optionalNullableTrimmedString, monthlyRent: optionalDecimalString, annualRent: optionalDecimalString, salePrice: optionalDecimalString, totalArea: optionalDecimalString, extractionAvailable: z.boolean().nullable().optional(), extractionPossible: z.boolean().nullable().optional(), gasAvailable: z.boolean().nullable().optional(), threePhaseAvailable: z.boolean().nullable().optional(), authorizedActivities: z.array(z.string().trim()).default([]), restrictedActivities: z.array(z.string().trim()).default([]), internalComment: optionalNullableTrimmedString, assignedUserId: z.string().cuid().nullable().optional(), isPublishable: z.boolean().default(false) });
export const updatePropertySchema = createPropertySchema.partial();
export type CreatePropertyInput = z.infer<typeof createPropertySchema>;
export type UpdatePropertyInput = z.infer<typeof updatePropertySchema>;
