"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState("admin@premium-retail.fr");
  const [password, setPassword] = useState("password123");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(null); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) { const json = await response.json(); throw new Error(json.error || "Connexion impossible"); } router.push("/app/accueil"); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Erreur inconnue"); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center px-4 py-10"><div className="grid w-full max-w-6xl overflow-hidden rounded-[32px] border border-black/10 bg-white shadow-xl lg:grid-cols-[1.1fr_0.9fr]"><section className="hidden bg-[#171717] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="text-xs uppercase tracking-[0.2em] text-white/50">Immobilier commercial</div><h1 className="mt-6 max-w-md text-5xl font-semibold tracking-tight">L’outil métier premium pour piloter votre agence.</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/70">Biens, demandes, prospection terrain, dossiers, publication et suivi client réunis.</p></div><div className="text-sm text-white/50">Paris · Retail · Off-market · Suivi sur-mesure</div></section><section className="p-8 md:p-12"><div className="mx-auto max-w-md"><div className="text-sm uppercase tracking-[0.2em] text-neutral-400">Connexion</div><h2 className="mt-4 text-3xl font-semibold tracking-tight">Bienvenue</h2><p className="mt-2 text-sm leading-6 text-neutral-500">Connectez-vous pour accéder à votre espace de gestion.</p><form onSubmit={handleSubmit} className="mt-10 space-y-5"><label className="block space-y-2"><span className="text-sm font-medium">Email</span><input type="email" className="w-full rounded-2xl border border-black/10 px-4 py-3 outline-none focus:border-black/20" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label className="block space-y-2"><span className="text-sm font-medium">Mot de passe</span><input type="password" className="w-full rounded-2xl border border-black/10 px-4 py-3 outline-none focus:border-black/20" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{error && <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<button type="submit" disabled={loading} className="w-full rounded-2xl bg-black px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{loading ? "Connexion..." : "Se connecter"}</button></form></div></section></div></main>;
}
